version: '3'
services:
  python3:
    restart: always
    build: ./
    container_name: 'aws-test'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    ports:
      - 8080:8080
